version: '3.9'
services:
  postgres:
    image: postgres:15-alpine
    container_name: crypto-serv-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: serv
      POSTGRES_PASSWORD: serv
      POSTGRES_DB: crypto_serv
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
    container_name: crypto-serv-redis
    command: ["redis-server", "--save", "", "--appendonly", "no"]
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  minio:
    image: minio/minio:RELEASE.2024-03-15T01-07-19Z
    container_name: crypto-serv-minio
    command: server /data --console-address :9001
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    volumes:
      - minio_data:/data
volumes:
  postgres_data:
  redis_data:
  minio_data:
